#!/usr/bin/env bash
#
# purrbrews-mac.sh — the fleet's cloned MAC addresses.
#
# Each node's wired interface carries a fixed MAC (set by purrbrews-init.sh's
# network step), so the router, Pi-hole reservations and ARP tables see the
# same identity no matter which NIC or reinstall is behind it. MACs come from
# NODE_MACS in the env file, or are derived from the node name — see
# lib/node-mac.sh.
#
# Usage:
#   bash purrbrews-mac.sh list [--format table|dnsmasq|pihole|csv] [--env FILE]
#       Every node's name, IP and MAC. Runs anywhere with bash 4 (Git Bash too),
#       no root needed. Formats:
#         table    human-readable (default)
#         dnsmasq  dhcp-host=MAC,IP,name   — dnsmasq / Pi-hole custom config
#         pihole   Pi-hole v6 pihole.toml  dhcp.hosts array
#         csv      name,ip,mac
#
#   bash purrbrews-mac.sh show [--env FILE]
#       On a node: its expected MAC vs. what the interface actually has.
#
#   sudo bash purrbrews-mac.sh apply [--yes] [--env FILE]
#       On a node: set the cloned MAC (and static IP) now. Same code path as
#       'purrbrews-init.sh --only network' — detached, with auto-rollback.
#
set -Eeuo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Reuse the init script's env parsing and MAC map (it only runs main() when executed).
# shellcheck source=purrbrews-init.sh
. "${HERE}/purrbrews-init.sh"
trap - ERR

cmd="${1:-list}"; [[ $# -gt 0 ]] && shift
CURRENT_STEP="$cmd"
FORMAT=table
PASS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --format) FORMAT="${2:?--format needs a value}"; shift 2 ;;
    --env)    ENV_FILE="$(realpath -m "${2:?--env needs a file}")"; PASS+=(--env "$ENV_FILE"); shift 2 ;;
    --yes|-y) PASS+=(--yes); shift ;;
    -h|--help) sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

sorted_nodes() {  # by last IP octet
  local n
  for n in "${!NODE_IP[@]}"; do printf '%s %s\n' "${NODE_IP[$n]##*.}" "$n"; done | sort -n | cut -d' ' -f2
}

case "$cmd" in
  list)
    resolve_config
    [[ "$CLONE_MAC" == true ]] || warn "CLONE_MAC=false — these MACs are NOT applied to the nodes."
    case "$FORMAT" in
      table)
        printf '%-12s %-15s %-17s %s\n' NODE IP MAC SOURCE
        for n in $(sorted_nodes); do
          src=derived; [[ "${NODE_MAC[$n]}" != "$(derive_mac "$n")" ]] && src=NODE_MACS
          printf '%-12s %-15s %-17s %s\n' "$n" "${NODE_IP[$n]}" "${NODE_MAC[$n]}" "$src"
        done ;;
      dnsmasq)
        echo "# purrbrews fleet — static leases (generated by purrbrews-mac.sh)"
        for n in $(sorted_nodes); do printf 'dhcp-host=%s,%s,%s\n' "${NODE_MAC[$n]}" "${NODE_IP[$n]}" "$n"; done ;;
      pihole)
        echo "# pihole.toml → [dhcp] section (or: Settings → DHCP → Static DHCP configuration)"
        printf 'hosts = [\n'
        for n in $(sorted_nodes); do printf '  "%s,%s,%s",\n' "${NODE_MAC[$n]}" "${NODE_IP[$n]}" "$n"; done
        printf ']\n' ;;
      csv)
        echo "name,ip,mac"
        for n in $(sorted_nodes); do printf '%s,%s,%s\n' "$n" "${NODE_IP[$n]}" "${NODE_MAC[$n]}"; done ;;
      *) die "Unknown format '$FORMAT' (table, dnsmasq, pihole, csv)." ;;
    esac ;;

  show)
    resolve_config
    node="$(canonical_node "$(hostname -s)")" || die "This machine's hostname '$(hostname -s)' is not in NODE_IPS."
    iface="$(ip -4 route show default | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')"
    [[ -n "$iface" ]] || die "No default route."
    cur="$(cat "/sys/class/net/${iface}/address")"
    perm="$(ethtool -P "$iface" 2>/dev/null | grep -Eio '([0-9a-f]{2}:){5}[0-9a-f]{2}')" || true
    [[ "$perm" == "00:00:00:00:00:00" ]] && perm=""
    printf 'Node        %s\nInterface   %s\nExpected    %s (CLONE_MAC=%s)\nCurrent     %s\nBurned-in   %s   ← use this one for Wake-on-LAN\nIP          %s (expected %s)\n' \
      "$node" "$iface" "${NODE_MAC[$node]}" "$CLONE_MAC" "$cur" "${perm:-unknown (install ethtool)}" \
      "$(ip -4 -o addr show dev "$iface" | awk '{print $4}' | head -1)" "${NODE_IP[$node]}/${SUBNET_CIDR}"
    if [[ "$CLONE_MAC" == true && "$cur" != "${NODE_MAC[$node]}" ]]; then
      echo "→ MAC not applied yet: sudo bash $0 apply"; exit 1
    fi
    echo "→ OK" ;;

  apply)
    exec bash "${HERE}/purrbrews-init.sh" --only network "${PASS[@]}" ;;

  *) die "Unknown command '$cmd' (list, show, apply). See --help." ;;
esac
