# For the Postgres recorder. Home Assistant won't create the database itself,
# so postgres-homeassistant does, from these, on its first start.
HA_DB_USERNAME       value homeassistant
HA_DB_PASSWORD       hex 64
HA_DB_DATABASE_NAME  value homeassistant
